# Copyright 2024 The LiteRT Torch Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Provides a configuration for the litert-torch."""

import logging
import os

__all__ = ["config"]


def _get_bool_env_var(name: str, default: bool) -> bool:
  var = os.environ.get(name, "y" if default else "n")
  var = var.lower().strip()
  if var in ("y", "yes", "t", "true", "on", "1"):
    return True
  elif var in ("n", "no", "f", "false", "off", "0"):
    return False
  else:
    logging.warning("Invalid %s value is ignored: %r.", name, var)
    return default


def _get_int_env_var(name: str, default: int) -> int:
  var = os.environ.get(name, str(default))
  var = var.strip()
  if var.isdigit():
    return int(var)
  else:
    logging.warning("Invalid %s value is ignored: %r.", name, var)
    return default


class _Config:
  """litert-torch global configs."""

  @property
  def in_oss(self) -> bool:
    """True if the code is not running in google internal environment."""
    return True

  @property
  def enable_group_norm_composite(self) -> bool:
    """True if lowering group norm in StableHLO composite.

    Currently only supports NHWC group norm generated by
    OptimizeLayoutTransposesPass.
    """
    return _get_bool_env_var("ENABLE_GROUP_NORM_COMPOSITE", default=False)

  @enable_group_norm_composite.setter
  def enable_group_norm_composite(self, value: bool) -> None:
    os.environ["ENABLE_GROUP_NORM_COMPOSITE"] = "y" if value else "n"

  @property
  def layout_optimize_partitioner(self) -> str:
    """The algorithm to use for layout optimization."""
    return os.environ.get("LAYOUT_OPTIMIZE_PARTITIONER", "DEFAULT")

  @layout_optimize_partitioner.setter
  def layout_optimize_partitioner(self, value: str) -> None:
    os.environ["LAYOUT_OPTIMIZE_PARTITIONER"] = str(value).upper()

  @property
  def lazy_constant_numel_threshold(self) -> int:
    """The threshold for the number of elements in a constant to be eligible to be lazily loaded during lightweight conversion."""
    default = 1024 * 1024  # 1MB
    return _get_int_env_var("LAZY_CONSTANT_NUMEL_THRESHOLD", default=default)

  @lazy_constant_numel_threshold.setter
  def lazy_constant_numel_threshold(self, value: int) -> None:
    os.environ["LAZY_CONSTANT_NUMEL_THRESHOLD"] = str(value)

  @property
  def lazy_constant_getter_chunk_size(self) -> int:
    """The chunk size for the lazy constant getter during lightweight conversion."""
    default = 32 * 1024 * 1024  # 32MB
    return _get_int_env_var("LAZY_CONSTANT_GETTER_CHUNK_SIZE", default=default)

  @lazy_constant_getter_chunk_size.setter
  def lazy_constant_getter_chunk_size(self, value: int) -> None:
    os.environ["LAZY_CONSTANT_GETTER_CHUNK_SIZE"] = str(value)


config = _Config()
